[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "greetme"
version = "0.0.1"
dependencies = []

[tool.setuptools.packages.find]
include = ["greetme"]
exclude = ["old"]

